import type { Metadata } from 'next';
import './globals.css';
import { auth } from '@/config/auth';
import { signOut } from 'next-auth/react';
import { ReactNode } from 'react';
import { roboto } from '@/config/fonts';
import { Button } from '@/lib/button/Button';
import { MainSideBar } from '@/lib/mainSideBar/MainSideBar';

export const metadata: Metadata = {
  title: 'Investment Advisor',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${roboto.className} ml-16 text-cyan-950`}>
        {!session?.user && (
          <Button onClick={async () => signOut()}>Log out</Button>
        )}
        {session?.user && (
          <>
            <MainSideBar user={session.user} onLogOut={signOut} />
            {children}
          </>
        )}
      </body>
    </html>
  );
}
