import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { MainSideBar } from '@/app/lib/mainSideBar/MainSideBar';
import { auth } from '@/app/config/auth';
import { Button } from '@/app/lib/button/Button';
import { signOut } from 'next-auth/react';
import { ReactNode } from 'react';

const roboto = Roboto({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Investment Advisor',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${roboto.className} ml-16 text-cyan-950`}>
        {!session?.user && (
          <Button onClick={async () => signOut()}>Log out</Button>
        )}
        {session?.user && (
          <>
            <MainSideBar user={session.user} onLogOut={signOut}/>
            {children}
          </>
        )}
      </body>
    </html>
  );
}
